version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-testdb}
      DB_USER: ${DB_USER:-root}
      DB_PASS: ${DB_PASS:-password}
    command: npm start
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-password}
      MYSQL_DATABASE: ${DB_NAME:-testdb}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASS:-password}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
